### ISSUE TITLE
Add a Delete Button to the Color Palate Generated

### ISSUE THREAD

**Issue by TheOpenInnovator** [TheOpenInnovator/ChromaVerse#1]
The Color Palate Generated has only save and share option, but doesn't have the Delete Option.
So add the delete button with :
- Proper Functionality
- Appropriate Icon
- Similar CSS as of other Options
- Appropriate Position in accordance to the other buttons

**Comment by MuhammedJaseemVK** [comment]
@TheOpenInnovator Can you assign this issue to me. I would like to work on it

**Comment by TheOpenInnovator** [comment]
Sure @MuhammedJaseemVK You  can start working on this issue.

**Comment by 2021eo3ar** [comment]
@TheOpenInnovator could you please assign me this issue.

**Comment by MuhammedJaseemVK** [comment]
@TheOpenInnovator Hi. I have made another PR #16 that fixes the rendering issue. Please do review and do merge
