### ISSUE TITLE
Implement "Copy All Codes" Feature for Color Palette in share window UI

### ISSUE THREAD

**Issue by HarshitaJaiswal5** [TheOpenInnovator/ChromaVerse#12]
The existing "Copy Code" option in the share functionality does not currently display the codes of the active color palette. We need to implement a feature that ensures the current palette codes are visible before users attempt to copy them. 

Requirements:
1. Display Active Palette Codes: Ensure that the codes for the current color palette are clearly displayed in the UI.
2. Smooth Functionality: Guarantee that the "Copy Codes" option works flawlessly, allowing users to copy the displayed codes easily.

<img width="960" alt="Screenshot 2024-10-12 031316" src="https://github.com/user-attachments/assets/b9c29fd8-fb0c-4202-a2ba-aee140ff17c2">

**Comment by HarshitaJaiswal5** [comment]
hey! @TheOpenInnovator can you assign me this issue under hacktoberfest?

**Comment by TheOpenInnovator** [comment]
That's great @HarshitaJaiswal5 for creating a valuable issue. You can start working on it.
