### ISSUE TITLE
Fix the UI of the Share Option

### ISSUE THREAD

**Issue by TheOpenInnovator** [TheOpenInnovator/ChromaVerse#3]
The current Share option has some UI defect, which is shown in the below attached Screenshot. Fix it such that the whole of the Share functionality is shown completely.

![image](https://github.com/user-attachments/assets/3ba0e664-f98b-43b7-b545-8dc910869264)

**Comment by HarshitaJaiswal5** [comment]
I am interested to fix this issue . @TheOpenInnovator  Can you assign this issue to me?

**Comment by TheOpenInnovator** [comment]
Hey @HarshitaJaiswal5 the issue has been assigned to you. You can start working on this. Make sure to fix the issue so that the snapshot generated looks professional and premium with proper and required changes fixed. Looking forward for you valuable contribution.
