### ISSUE TITLE
Fix the User Name Functionality

### ISSUE THREAD

**Issue by TheOpenInnovator** [TheOpenInnovator/ChromaVerse#4]
The Add User Name Functionality doesn't have any Enter or Edit Button.
The current version of that functionality is attached in the screen shot below. Do add the 
**Enter , Delete & Edit Button** for the **User Name** Option which will be shown on the Snap Shot generated.

![image](https://github.com/user-attachments/assets/0914dd91-4d09-4c1f-a7e4-7ae5f94a1dc7)

**Comment by AnshMehta24** [comment]
I'm Interested in solving this issue. Can you assign this to me??

**Comment by AnshMehta24** [comment]
## i have fixed this functionality. and plz go through my PR and Accept it if it is align with your requirements.

# Preview:

https://github.com/user-attachments/assets/4c820f2e-3570-494c-8a39-ad7f3fb7753f

**Comment by swarupsahu08** [comment]
Hey @TheOpenInnovator Can you assign me this issue

**Comment by AnshMehta24** [comment]
## Hey @swarupsahu08 , I have already completed this issue. just waiting for the review.

**Comment by swarupsahu08** [comment]
> ## Hey @swarupsahu08 , I have already completed this issue. just waiting for the review.
> 

ok thats great @AnshMehta24 can you suggest me any other project so that I can contribute

**Comment by TheOpenInnovator** [comment]
> > ## Hey @swarupsahu08 , I have already completed this issue. just waiting for the review.
> 
> ok thats great @AnshMehta24 can you suggest me any other project so that I can contribute

@swarupsahu08 You can have a look at all of our projects and curate issues on your own and start contributing. Looking forward to your contribution.

**Comment by swarupsahu08** [comment]
> > > ## Hey @swarupsahu08 , I have already completed this issue. just waiting for the review.
> > 
> > ok thats great @AnshMehta24 can you suggest me any other project so that I can contribute
> 
> @swarupsahu08 You can have a look at all of our projects and curate issues on your own and start contributing. Looking forward to your contribution.

@TheOpenInnovator ok I will try
